import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navLinkStyle: React.CSSProperties = {
  color: "#222",
  textDecoration: "none",
  fontWeight: 500,
  fontSize: 18,
  padding: "6px 16px",
  borderRadius: 6,
  transition: "background 0.2s",
  marginLeft: 4,
  marginRight: 4,
  background: "#f0f0f0",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body style={{ minHeight: "100vh", background: "#f6f8fa", margin: 0 }}>
        <nav style={{
          display: "flex",
          gap: 16,
          padding: "20px 32px",
          background: "#fff",
          boxShadow: "0 2px 8px rgba(0,0,0,0.04)",
          alignItems: "center",
          marginBottom: 32,
        }}>
          <span style={{ fontWeight: 700, fontSize: 22, color: "#0070f3", letterSpacing: 1 }}>Task Render Demo</span>
          <div style={{ flex: 1 }} />
          <Link href="/task-ssr" style={navLinkStyle}>Home</Link>
          <Link href="/task-ssr" style={navLinkStyle}>SSR</Link>
          <Link href="/task-ssg" style={navLinkStyle}>SSG</Link>
          <Link href="/task-isr/1" style={navLinkStyle}>ISR</Link>
          <Link href="/task-csr" style={navLinkStyle}>CSR</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
